# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplektSK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('weight', models.FloatField(blank=True, verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='ComplektSKCal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('number', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('summ', models.FloatField(blank=True, verbose_name='Сумма')),
                ('weight', models.FloatField(blank=True, verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='ComplektSKCalc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('number', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('weight', models.FloatField(blank=True, verbose_name='Вес')),
            ],
            managers=[
                ('summ', django.db.models.manager.Manager()),
            ],
        ),
    ]
